### PR TITLE
Fix for #8 D50 hickup

### PR DESCRIPTION
**Pull request by mheidt**
- every read() is of size 1
- no verbose switch anymore
- option to compile with #ifdef DEBUG

### CODE REVIEW

**Comment by falkTX** [comment]
I am not sure if this is meant as a serious PR...
There are many small things that are not good, for example changing code style and indentation, which has nothing to do with the functionality in question.
Also the 2nd for loop is not needed, since it will always only run once.

Please clean it up if you want to see it merged.

tbh I disagree with the removal of verbose mode argument.
having to build a new binary just to change functionality of a program is not nice, specially when we can make it work with a simple switch.

**Comment by mheidt** [comment]
Sorry, I had to develope with vi.
The verbose mode hasn't had any functionality.  There was not a single action done if you selected -v
Regarding braces...I saw different styles already, so that I didn't know, which was in your faviour.

**Comment by mheidt** [comment]
Please check again.

**Comment by falkTX** [comment]
getting better, but still a few things... 
- the very few lines in the diff change unrelated things (yes, code is not consistent, but if we are to fix styling, there should be a dedicated PR/patch for that)
- the last changed you made are missing newline at the end of the string
- the `#undef DEBUG` is unwanted. DEBUG/NDEBUG macros ought to be controlled by the build type - debug or release. not sure if ttymidi has ways to build those separately though

**Comment by mheidt** [comment]
I used undef to tell future developers, that there is the option to #define it.
I can remove it.
What lines are not ok?

**Comment by falkTX** [comment]
If you have a look at the entire diff of this PR, you can see for yourself.
https://github.com/moddevices/mod-ttymidi/pull/9/files

**Comment by mheidt** [comment]
I know. and on that page...what line is not ok?

**Comment by mheidt** [comment]
why don't you reject the PR and fix it the way you like?
I am happy to test it.

**Comment by falkTX** [comment]
I thought it was more obvious, sorry.
As I said, the diff shows a few changes that have nothing to do with the target, just small changes in code style and indentation. Those are not wanted in a PR (speaking in general, not just this one). It is often better to leave things clean, only touch the real essential bits.

In any case, does it help to find out a resolution of the main issue #8 ?

**Comment by mheidt** [comment]
The other changes were needed in order to find the bug.
I find them quite convenient for future debugging as well.
If you don't like them, it's best if you pick the parts that are needed for the fix and apply them yourself

**Comment by falkTX** [comment]
See bd84df86f3cf3ccfcafbb61c3b8af5d435af0a0f
The verbose mode switch now does what this PR needs

**Pull request closed without merging**
