### PR TITLE
Fix for #8 D50 Hickup

### PR DESCRIPTION
**Pull request by mheidt**

### CODE REVIEW

**Comment by falkTX** [comment]
oh, so this is basically the failure to check the `read` status. Makes a lot of sense actually, thanks for the discovery!

The code does not seem right though, mainly this:
```
read_cnt += read(serial, buffer+1+read_cnt, data_bytes_cnt-read_cnt);
```
you do `buffer+1+read_cnt`, but old code had simply `buffer+1`.

The issue I see is that read_cnt always starts at 1, otherwise this part of the code is not reached.
Which means the read actually uses at least `buffer+2`

**Comment by mheidt** [comment]
I tested it.
I had to add read_cnt, because that's the offset where the previous read failed.
And as I wanted to have the correct verbose message, I had to introduce the offset variable.

**Comment by falkTX** [comment]
I made quite a few changes just now, taking this issue into account.
Please try it and let me know if it works for now.

I see the code is quite messy regarding style, I want to clean that.
But I will wait until confirmation from your side that all is okay, in case you need to do changes in the code.

**Comment by mheidt** [comment]
I have compiling issues

root@zynthian:/zynthian/zynthian-sw/mod-ttymidi# git log
commit 27cce4873e8f6d1218a061df1c103da816e356c4 (HEAD -> master, origin/master, origin/HEAD)
Author: falkTX <falktx@falktx.com>
Date:   Thu Dec 12 22:45:30 2019 +0000

    Remove silent mode switch, did nothing
    
    Signed-off-by: falkTX <falktx@falktx.com>

commit 8b5ff45ce0253748d8ed09549b202dd22bb180e5
Author: falkTX <falktx@falktx.com>
Date:   Thu Dec 12 22:42:29 2019 +0000

    verbose and printonly modes only available in debug builds
    
    Signed-off-by: falkTX <falktx@falktx.com>

commit f9f9f0887dfebabefbd6dd23f47155b3dbf13531
Author: falkTX <falktx@falktx.com>
Date:   Thu Dec 12 22:38:08 2019 +0000

    Add make debug option
    
root@zynthian:/zynthian/zynthian-sw/mod-ttymidi# 
root@zynthian:/zynthian/zynthian-sw/mod-ttymidi# make 
cc src/ttymidi.c -mcpu=cortex-a53 -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mlittle-endian -munaligned-access -mvectorize-with-neon-quad -ftree-vectorize -std=gnu99 -Wall -Wextra -Wshadow -Werror -fvisibility=hidden -O2 -DNDEBUG -I/usr/local/include -L/usr/local/lib -ljack -Wl,--no-undefined -lpthread -o ttymidi
src/ttymidi.c: In function ‘parse_opt’:
src/ttymidi.c:119:4: error: ‘strncpy’ specified bound 32 equals destination size [-Werror=stringop-truncation]
    strncpy(arguments->serialdevice, arg, MAX_DEV_STR_LEN);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ttymidi.c: In function ‘jack_initialize’:
src/ttymidi.c:820:13: error: ‘strncpy’ specified bound 32 equals destination size [-Werror=stringop-truncation]
             strncpy(arguments.serialdevice, load_init, MAX_DEV_STR_LEN);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:21: ttymidi] Error 1

**Comment by mheidt** [comment]
make install DEBUG=1
works

**Comment by mheidt** [comment]
and as the new code is checking the read flag, the hickup is gone

**Pull request closed without merging**
